name: Release

on:
  push:
    tags: ["v*"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Build Gem
        run: gem build
      - name: Release Gem to Rubygems
        run: gem push *.gem
